### ISSUE TITLE
Todo App Delete 기능 구현

### ISSUE THREAD

**Issue by yjyaang** [yjyaang/pre-project-todo-app#5]
### 만들고자 하는 기능
Todo App Delete 기능 구현

### 기능 구현을 위해 필요한 일
- [ ] 쓰레기통 아이콘을 누르면 데이터가 지워지도록 onClick 함수 구현
- [ ] 삭제된 후 화면이 리렌더링되어 지운 결과가 Read에 반영되도록 구현
- [ ] 서버에 있는 데이터도 삭제되도록 기능 구현

### 예상 소요 시간
3h
