### ISSUE TITLE
Todo App Update 기능 구현

### ISSUE THREAD

**Issue by yjyaang** [yjyaang/pre-project-todo-app#6]
### 만들고자 하는 기능
Todo App Update 기능 구현

### 기능 구현을 위해 필요한 일
- [ ] 수정 버튼을 누르면 텍스트 영역이 input으로 바뀌는 기능 구현(텍스트는 그대로 유지)
- [ ] 완료 버튼을 눌렀을 때 수정 결과가 반영되는 onClick 함수 구현
- [ ] 수정 결과가 서버에 저장되도록 기능 구현

### 예상 소요 시간
3h
